# Generated by Django 3.0.3 on 2020-03-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_auto_20200228_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
